
INSERT INTO teacher (id, name, qualification)
VALUES
(1, 'John Smith', 'Bachelor of Science in Mathematics'),
(2, 'Alice Johnson', 'Master of Arts in English Literature'),
(3, 'Michael Williams', 'Bachelor of Education in Physics'),
(4, 'Emily Brown', 'Master of Science in Chemistry'),
(5, 'James Taylor', 'Bachelor of Arts in History'),
(6, 'Sarah Anderson', 'Master of Education in Biology'),
(7, 'Matthew Martinez', 'Bachelor of Science in Computer Science'),
(8, 'Emma Jones', 'Master of Arts in Psychology'),
(9, 'Olivia Garcia', 'Bachelor of Education in Geography'),
(10, 'Daniel Wilson', 'Master of Science in Economics'),
(11, 'Sophia Brown', 'Bachelor of Science in Mathematics'),
(12, 'David Wilson', 'Master of Arts in English Literature'),
(13, 'Isabella Thompson', 'Bachelor of Education in Physics'),
(14, 'Ethan Clark', 'Master of Science in Chemistry'),
(15, 'Ava Hall', 'Bachelor of Arts in History'),
(16, 'Mia Lee', 'Master of Education in Biology'),
(17, 'Alexander King', 'Bachelor of Science in Computer Science'),
(18, 'Chloe Moore', 'Master of Arts in Psychology'),
(19, 'Benjamin Wright', 'Bachelor of Education in Geography'),
(20, 'Emily Taylor', 'Master of Science in Economics'),
(21, 'Jacob Harris', 'Bachelor of Science in Mathematics'),
(22, 'Madison Nelson', 'Master of Arts in English Literature'),
(23, 'William Martinez', 'Bachelor of Education in Physics'),
(24, 'Sophia Lewis', 'Master of Science in Chemistry'),
(25, 'Michael Brown', 'Bachelor of Arts in History'),
(26, 'Olivia Anderson', 'Master of Education in Biology'),
(27, 'James Smith', 'Bachelor of Science in Computer Science'),
(28, 'Emma Johnson', 'Master of Arts in Psychology'),
(29, 'Elijah Garcia', 'Bachelor of Education in Geography'),
(30, 'Abigail Wilson', 'Master of Science in Economics'),
(31, 'Charlotte Davis', 'Bachelor of Science in Mathematics'),
(32, 'Noah Wilson', 'Master of Arts in English Literature'),
(33, 'Avery Thompson', 'Bachelor of Education in Physics'),
(34, 'Ethan Robinson', 'Master of Science in Chemistry'),
(35, 'Sophia Young', 'Bachelor of Arts in History'),
(36, 'Liam Lee', 'Master of Education in Biology'),
(37, 'Isabella King', 'Bachelor of Science in Computer Science'),
(38, 'Mason Moore', 'Master of Arts in Psychology'),
(39, 'Ella Wright', 'Bachelor of Education in Geography'),
(40, 'David Taylor', 'Master of Science in Economics'),
(41, 'Ava Harris', 'Bachelor of Science in Mathematics'),
(42, 'Oliver Martinez', 'Master of Arts in English Literature'),
(43, 'Harper Lewis', 'Bachelor of Education in Physics'),
(44, 'Emma Brown', 'Master of Science in Chemistry'),
(45, 'Liam Hall', 'Bachelor of Arts in History'),
(46, 'Avery Anderson', 'Master of Education in Biology'),
(47, 'Lucas Smith', 'Bachelor of Science in Computer Science'),
(48, 'Mia Johnson', 'Master of Arts in Psychology'),
(49, 'Benjamin Garcia', 'Bachelor of Education in Geography'),
(50, 'Charlotte Wilson', 'Master of Science in Economics'),
(51, 'Mason Davis', 'Bachelor of Science in Mathematics'),
(52, 'Olivia Wilson', 'Master of Arts in English Literature'),
(53, 'Jackson Thompson', 'Bachelor of Education in Physics'),
(54, 'Ava Robinson', 'Master of Science in Chemistry'),
(55, 'Liam Young', 'Bachelor of Arts in History'),
(56, 'Sophia Lee', 'Master of Education in Biology'),
(57, 'Ethan King', 'Bachelor of Science in Computer Science'),
(58, 'Isabella Moore', 'Master of Arts in Psychology'),
(59, 'Jacob Wright', 'Bachelor of Education in Geography'),
(60, 'Charlotte Taylor', 'Master of Science in Economics'),
(61, 'Liam Harris', 'Bachelor of Science in Mathematics'),
(62, 'Emma Martinez', 'Master of Arts in English Literature'),
(63, 'Ella Lewis', 'Bachelor of Education in Physics'),
(64, 'Noah Brown', 'Master of Science in Chemistry'),
(65, 'Ava Hall', 'Bachelor of Arts in History'),
(66, 'Jackson Anderson', 'Master of Education in Biology'),
(67, 'Sophia Smith', 'Bachelor of Science in Computer Science'),
(68, 'Ethan Johnson', 'Master of Arts in Psychology'),
(69, 'Oliver Garcia', 'Bachelor of Education in Geography'),
(70, 'Emma Wilson', 'Master of Science in Economics'),
(71, 'Ava Davis', 'Bachelor of Science in Mathematics'),
(72, 'Olivia Wilson', 'Master of Arts in English Literature'),
(73, 'William Thompson', 'Bachelor of Education in Physics'),
(74, 'Emily Robinson', 'Master of Science in Chemistry'),
(75, 'Liam Young', 'Bachelor of Arts in History'),
(76, 'Sophia Lee', 'Master of Education in Biology'),
(77, 'Ethan King', 'Bachelor of Science in Computer Science'),
(78, 'Isabella Moore', 'Master of Arts in Psychology'),
(79, 'Jacob Wright', 'Bachelor of Education in Geography'),
(80, 'Charlotte Taylor', 'Master of Science in Economics'),
(81, 'Liam Harris', 'Bachelor of Science in Mathematics'),
(82, 'Emma Martinez', 'Master of Arts in English Literature'),
(83, 'Ella Lewis', 'Bachelor of Education in Physics'),
(84, 'Noah Brown', 'Master of Science in Chemistry'),
(85, 'Ava Hall', 'Bachelor of Arts in History'),
(86, 'Jackson Anderson', 'Master of Education in Biology'),
(87, 'Sophia Smith', 'Bachelor of Science in Computer Science'),
(88, 'Ethan Johnson', 'Master of Arts in Psychology'),
(89, 'Oliver Garcia', 'Bachelor of Education in Geography'),
(90, 'Emma Wilson', 'Master of Science in Economics'),
(91, 'Ava Davis', 'Bachelor of Science in Mathematics'),
(92, 'Olivia Wilson', 'Master of Arts in English Literature'),
(93, 'William Thompson', 'Bachelor of Education in Physics'),
(94, 'Emily Robinson', 'Master of Science in Chemistry'),
(95, 'Liam Young', 'Bachelor of Arts in History'),
(96, 'Sophia Lee', 'Master of Education in Biology'),
(97, 'Ethan King', 'Bachelor of Science in Computer Science'),
(98, 'Isabella Moore', 'Master of Arts in Psychology'),
(99, 'Jacob Wright', 'Bachelor of Education in Geography'),
(100, 'Charlotte Taylor', 'Master of Science in Economics');

